project:
  type: website

website:
  title: "97039"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Module 1.qmd
      - Module 2.qmd
      - Module 3.qmd

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

editor: visual

